### ISSUE TITLE
ESP8266 TCP Source Port Uses Fixed Sequence

### ISSUE THREAD

**Issue by brandond** [me-no-dev/ESPAsyncTCP#108]
There is an issue with the esp8266 lwip library where the tcp_new() function uses a fixed sequence of source ports every time. This means that a node that is rebooting frequently and reconnecting to the same server may experience issues due to the host perceiving the packets as being retransmissions of old traffic - they have the exact same source, destination, and initial sequence number.

This has been reported and discussed in the Arduino core in https://github.com/esp8266/Arduino/issues/632; their fix was to allow the user to call `setLocalPortStart()`, which sets an initial source port that is used (and incremented) to override `local_port` within the `tcp_pcb` returned by `tcp_new()`.

Does ESPAsyncTCP have a work-around for this issue, and if not, could one be added? I believe I'm experiencing occasional dropped traffic caused by this oddity.

**Comment by mcspr** [comment]
@brandond just so you're aware, most recent Core version has a different approach for this. see esp8266/Arduino#5906

**Comment by brandond** [comment]
So is this fixed, or just fixed in a different version of the lib?

**Comment by mcspr** [comment]
Should be fixed upstream, Core >=2.5.2 with lwip2 selected will randomize ports by default
