### ISSUE TITLE
Supported?

### ISSUE THREAD

**Issue by fmarzocca** [me-no-dev/ESPAsyncTCP#137]
Is this library still supported?

**Comment by kleini** [comment]
I would say yes, but progress of merge requests is not very fast.

**Comment by fmarzocca** [comment]
Thanks, I'm interested to know if TLS 1.2 is supported.

**Comment by kleini** [comment]
I have no idea about the implementation. But I know, ESP devices are very limited in memory and they already have to make a lot of hard optimizations to be able to encrypt and decrypt with 80K of memory. Newer encryption mechanisms normally require more amount of memory. Maybe it is possible, I just don't know, but it will be very hard to implement.
