### ISSUE TITLE
AsyncWebServer - ESPAsyncTCP connecting after VPN

### ISSUE THREAD

**Issue by karacaozan** [me-no-dev/ESPAsyncTCP#16]
Hi, 
Have you tried connecting the async web server via VPN? I cannot access to the Async Webserver when on vpn. 
there is openVPN installed on my RPi-3, assigns 10.8.0.x IPs to VPN clients, routing is in place for 192.168.1.x in iptables. Works very well for any other device in the network, but  hangs for Async Web server. I am not sure if there is something wrong with my routing rules, any idea?

*Same setup was working with standard ESP8266WebServer library before. 

Thank you very much, 
Best,

**Comment by me-no-dev** [comment]
hmmm if it's working with ESP8266WebServer it should work here as well. Maybe MSS issues again and the ESP does not handle fragmentation.

**Comment by me-no-dev** [comment]
should be fixed now!
