### ISSUE TITLE
fatal error: include/ssl.h: No such file or directory

### ISSUE THREAD

**Issue by ohyeaah** [me-no-dev/ESPAsyncTCP#174]
Hello,
I have a Wemos D1 mini pro board with an ESP8266EX processor.

I get the above error but I don't know why.

There is no ssl.h file in the whole board source code folder.
But there is bearssl.h. Maybe this is the solution?

Can anyone help?

**Comment by n0valis** [comment]
I have the same problem. I think it has to do with build_flags = -DASYNC_TCP_SSL_ENABLED=1
related to
https://github.com/me-no-dev/ESPAsyncTCP/pull/129

But I dont know how to fix this other than set ASYNC_TCP_SSL_ENABLED to 0
