### ISSUE TITLE
library is broken

### ISSUE THREAD

**Issue by juergmaier** [me-no-dev/ESPAsyncTCP#178]
I installed the zip version for my esp8266 as it is not part of official arduino ibraries?
It installs in arduino libraries folder AsyncTCP-master/
in the src folder the files are  named AsyncTCP
an include <ESPAsyncTCP> in my sketch throws an error
trying to include it as <AsyncTCP> throws an error with non existing sdkconfig.h and freertos/semphr.h
commenting these out looks to work but later ESPAsyncWebServer references <ESPAsyncTCP.h> which it can't find.

**Comment by AquaCobell** [comment]
same here

**Comment by Marisa-Chan** [comment]
Just remove "-master" from unpacked folder name. It must be just "AsyncTCP"
