### ISSUE TITLE
Why are there no active releases available for download?

### ISSUE THREAD

**Issue by pdfelen** [me-no-dev/ESPAsyncTCP#183]
Hi,

I'm using ESPAsyncWebServer for quite some time. I was trying to update my libraries to the latest versions, but there were no published releases available.

Would be nice it will be there again.

Thanks a lot.

Pepijn

**Comment by MacDada** [comment]
> @[stale](https://github.com/apps/stale) stale bot closed this as [completed](https://github.com/me-no-dev/ESPAsyncTCP/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [2 hours ago](https://github.com/me-no-dev/ESPAsyncTCP/issues/183#event-9560497931)

This issue is not resolved.
