### ISSUE TITLE
ASYNC_TCP_SSL_ENABLED to 1 cause multiple definition error 

### ISSUE THREAD

**Issue by yhua537** [me-no-dev/ESPAsyncTCP#22]
This likely to be known problem for you: After changing the default of  ASYNC_TCP_SSL_ENABLED to 1 in config.h, with the master version of espAsyncTCP and eSP8266WiFi, i got a problem with multiple definition of `ax_port_read' similar to [this issue](https://github.com/idolpx/mobile-rr/issues/12). 

Given disable is the default and [SSL support is open ticket](https://github.com/me-no-dev/ESPAsyncTCP/issues/9),  is that mean TLS server is not ready even if it is synchronous? Or, how do i fix this multiple definition error ?

**Comment by me-no-dev** [comment]
use git version of esp8266 ardiuino

**Comment by yhua537** [comment]
Great, it works, thank you
