### ISSUE TITLE
Example for the AsyncPrinter

### ISSUE THREAD

**Issue by ripleyXLR8** [me-no-dev/ESPAsyncTCP#30]
Hi,

Thank you for your work on this library, it is very usefull.

Do you have any example about using the AsyncPrinter?

Best regards

Richard

**Comment by psuter80** [comment]
here is an example using WiFiManager to connect to a wifi network first: 
```#include <ESP8266WiFi.h>          //ESP8266 Core WiFi Library (you most likely already have this in your sketch)
#include <DNSServer.h>            //Local DNS Server used for redirecting all requests to the configuration portal
#include <ESP8266WebServer.h>     //Local WebServer used to serve the configuration portal
#include <WiFiManager.h>          //https://github.com/tzapu/WiFiManager WiFi Configuration Magic
#include <AsyncPrinter.h>

AsyncPrinter ap;
WiFiManager wifiManager;
 
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  wifiManager.autoConnect();
  ap.connect("192.168.1.122",3333);
  ap.println("hello world");
}
 
void loop() {
  // put your main code here, to run repeatedly:
}
```
on the computer with ip 192.168.1.122 you need to listen to port 3333 to receive the hello world message. under linux you can use netcat: 
``nc -l 3333``

now upload and run the above sketch and you should see "hello world" printed to your console running netcat.
