### ISSUE TITLE
Compatibility with 2.3.0 esp8266/Arduino

### ISSUE THREAD

**Issue by akaJes** [me-no-dev/ESPAsyncTCP#33]
when enabled ssl option in your config 
`#define ASYNC_TCP_SSL_ENABLED 1`
appears compilation error for duplication your tcp_axtls.c with arduino WiFiClientSecure.cpp  
like ax_port_write and others functions/variables

**Comment by me-no-dev** [comment]
It's known problem with 2.3.0. Has been fixed in git, but has not been released yet.

**Comment by akaJes** [comment]
It is a good news :) 
ill wait Your update
