### ISSUE TITLE
rx timeout in ms

### ISSUE THREAD

**Issue by ittacco** [me-no-dev/ESPAsyncTCP#34]
Hi, I would suggest to have rx timeout expressed in ms instead of seconds. To be able to set a timeout lower than 1 sec, I'm currently forced to implement externally.
Thanks

**Comment by rahuldeo2047** [comment]
You can fork, implement and have a pull request.

**Comment by rahuldeo2047** [comment]
@ittacco : could you try that?

**Comment by rahuldeo2047** [comment]
![Screenshot_2019-11-03-23-06-23-80](https://user-images.githubusercontent.com/22162095/68089417-9cbdb400-fe8e-11e9-8321-60d5c33d4cac.png)

**Comment by rahuldeo2047** [comment]
@ittacco :reminder if possible.
