### ISSUE TITLE
Is ESP32 supported? 

### ISSUE THREAD

**Issue by n0f8r** [me-no-dev/ESPAsyncTCP#37]
Links2004 over at the arduinoWebSockets library thought that ESPAsyncTCP works on ESP32, but I've just had a pile of compile errors trying to include ESPAsyncTCP.

I've not been working with Arduino long and C is not my first language, so perhaps there's something obvious I need to do? The compile errors look like a conflict between different versions of a network library. For instance this is the first (and then loads more like that) : 

_C:\Arduino\libraries\ESPAsyncTCP-master\src\ESPAsyncTCP.cpp:113:36: error: macro "ip_route" requires 2 arguments, but only 1 given
   netif* interface = ip_route(&addr);_

**Comment by williamesp2015** [comment]
PlatformIo announced that ESPAsyncTCP is compatible with ESP32 but I got errors:

src\ESPAsyncTCP.cpp:468:6: error: prototype for 'void AsyncClient::_s_dns_found(const char*, ip_addr_t*, void*)' does not match any in class 
'AsyncClient'
void AsyncClient::_s_dns_found(const char *name, ip_addr_t *ipaddr, void *arg){
^
In file included from src\ESPAsyncTCP.cpp:24:0:
src\ESPAsyncTCP.h:100:17: error: candidate is: static void AsyncClient::_s_dns_found(const char*, ip_addr*, void*)
static void _s_dns_found(const char *name, struct ip_addr *ipaddr, void *arg);

^
src\ESPAsyncTCP.cpp: In member function 'uint32_t AsyncClient::getRemoteAddress()':
src\ESPAsyncTCP.cpp:566:26: error: 'ip_addr_t {aka struct _ip_addr}' has no member named 'addr'
return _pcb->remote_ip.addr;
^
src\ESPAsyncTCP.cpp: In member function 'uint32_t AsyncClient::getLocalAddress()':
src\ESPAsyncTCP.cpp:578:25: error: 'ip_addr_t {aka struct _ip_addr}' has no member named 'addr'
return _pcb->local_ip.addr;
^
src\ESPAsyncTCP.cpp: In member function 'void AsyncServer::begin()':
src\ESPAsyncTCP.cpp:824:14: error: 'ip_addr_t {aka struct _ip_addr}' has no member named 'addr'
local_addr.addr = (uint32_t) _addr;
^
*** [.pioenvs\esp32dev\src\ESPAsyncTCP.o] Error 1

**Comment by me-no-dev** [comment]
@ivankravets is that true? I never said it's compatible with ESP32?

**Comment by n0f8r** [comment]
@me-no-dev I'm not sure where the idea of ESP32 compatibility originated - but the dev behind the arduino web sockets library that I was using on ESP8266 also thought it was ESP32 compatible - of course I also ran into issues ...

Links2004 => "if I remember correct ESPAsyncTCP supports ESP32."

See here https://github.com/Links2004/arduinoWebSockets/issues/161

**Comment by me-no-dev** [comment]
it was true for ESP31B, but for ESP32 things are much much different.

**Comment by williamesp2015** [comment]
I have Websocket with ESPAsyncTCP and I need to use ESP32. Any help would be greatly appreciated.

**Comment by me-no-dev** [comment]
I have ESP32 and LOOOTS of work before I get to Async (which is my own project rather than my food paying job)

**Comment by ivankravets** [comment]
@me-no-dev That is something new 😊 

> PlatformIo announced that ESPAsyncTCP is compatible with ESP32 but I got errors

@williamesp2015 please sorry, who did announce? Please be careful with "Compatibility" information on a library page. See 

* http://platformio.org/lib/show/305/ESPAsyncTCP

**Comment by n0f8r** [comment]
@ivankravets  it's right there in the title tagline on the page you linked "Asynchronous TCP Library for ESP8266 and **ESP32**"

**Comment by ivankravets** [comment]
@me-no-dev gotcha! 😆 

* https://github.com/me-no-dev/ESPAsyncTCP/blame/master/library.json

**Comment by me-no-dev** [comment]
damned I thought I cleaned all of those...

**Comment by me-no-dev** [comment]
fixed!

**Comment by timpur** [comment]
Sorry to ask this question, But do you think this lib some day soon will be supported to work on the esp32?
Tim.

**Comment by camilorodegheri** [comment]
Hi, got a first version working on ESP32. There is more work to be done, but sharing with people to be evaluated.
#48

**Comment by me-no-dev** [comment]
Look [HERE](https://github.com/me-no-dev/AsyncTCP)
