### ISSUE TITLE
delay(xxx) causes crash while tcp_write()

### ISSUE THREAD

**Issue by mcr-ksh** [me-no-dev/ESPAsyncTCP#42]
Hi,

on any example that uses a read/write context simply put a delay(xxx) in the loop() function and the skatch will crash.

What other delay function would be safe?

Best,
M

**Comment by jeroenst** [comment]
I also am experiencing more crashes when using delays in code when using ESPAsyncTCP.

I had a project with some small delays, which was stable when using normal tcpserver but crashed after a few hours each time when using ESPAsyncTCP. After removing the delay and using millis() instead it is now stable for 3 days allready.
