### ISSUE TITLE
Http Post

### ISSUE THREAD

**Issue by paraflou** [me-no-dev/ESPAsyncTCP#43]
Hi there. I saw that was an issue with Http Post and it was closed without any reply.

I am trying to send a post request with an async client.

I did some debugging with wireshark to find out what is the raw post format (including \r\n 's) but i can't get it work.

I am trying sth like this to a dump rest server i have for testing. There is no need for content type. 
From a default rest client i just type anything to message body and post it nice n easy.

client->write("POST http://192.168.100.109:8089/myRest/getResponse HTTP/1.1\r\nHost: http://192.168.100.109:8089\r\n\r\nSomePostString");

Can i use post request with async client?

**Comment by bofh69** [comment]
This is a TCP-library, you can implement whatever TCP-protocol you want over it, including HTTP.

In your case:
I don't think you can have a message body without either a Content-Length or Transfer-Encoding header field in HTTP-1.1. I believe many HTTP-servers allow it anyway, but then you need to close the client->server stream for them to know that the whole body have been sent, however I'm not sure you can close just the client->server stream with this library. Anyway, use a Content-Length field, besides required by the standard, it will often make the server faster as well.

From [RFC2616 - HTTP/1.1](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3)
"The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers"
