### ISSUE TITLE
Using 2 ESPAsyncTCP Servers causing unexpected out-of-order sequence

### ISSUE THREAD

**Issue by pdfelen** [me-no-dev/ESPAsyncTCP#52]
ESPAsyncTCP and ESPAsyncWebServer are two very useful libraries! I'm working on some implementations and have ran into some questions

@me-no-dev 
A similar issue as #44 I'm experiencing when using 2 ESPAsyncTCP Servers (1 for control, 1 for data). The protocol (FTP) requires action on both clients:
ie 'MLSD' command received on control client [1], requires a response '150' being send on the control client [2], a directory listing to be sent on data client [3] and process termination by replying summary report via control client [4].
When trying to do this from the control.onData() function, the actual sending will be [1][2][4][3], causing the FTP sequence to fail. It seems that all action towards the data client are executed after control.onData() has finished.
Question 1: Is this intended behaviour?
Also processing control.onData() seems to block data.onClient()
Question 2: Is this intended behaviour?

Using a Handler() function in loop() is off course an option, but creating servers without the need of handlers was the beauty of Async implementation. ;-)

As alternative I found that using control.onPoll() can be used as synchronisation trigger. Setting a kind of callback and a selectable number of polls to wait and to make sure there is no overlap with control.onData() seems to work fine. In control.onData() the callback is enabled after the command is recognized [1a] and the control.onData() function is ended [1b]. On one of the next control.onPoll() events, the sequence [2][3][4] (numbers as before) is completed in order.
Question 3: Do you foresee any issues using onPoll() this way?

Thanks.

**Comment by me-no-dev** [comment]
Interesting stuff :) have not attempted FTP on Async yet :)
Surely there is no issue using the onPoll ;) that is why it's there :) Though there should be a way for you to do it without, but until I dive into it deeper I can not really recommend anything :(
onPoll is not called that often, so try to use as little onPolls as possible :)
