### ISSUE TITLE
Use of panic() on esp32?

### ISSUE THREAD

**Issue by andig** [me-no-dev/ESPAsyncTCP#53]
See https://github.com/me-no-dev/ESPAsyncTCP/blob/34d116f768f13d551066c6280fc78302e78861f1/src/ESPAsyncTCPbuffer.cpp#L35 and https://github.com/me-no-dev/ESPAsyncTCP/blob/34d116f768f13d551066c6280fc78302e78861f1/src/ESPAsyncTCPbuffer.cpp#L128 both using `panic()` which doesn't seem to exist on ESP32?

**Comment by me-no-dev** [comment]
The buffer class is not in AsyncTCP which is the ESP32 lib

**Comment by me-no-dev** [comment]
Different lib is used on the other mcu

**Comment by me-no-dev** [comment]
If added there it will be modified ;)

**Comment by andig** [comment]
Haha, didn't even notice that AsyncTCP is new. Excuse me ;)
