### ISSUE TITLE
2.3.0  ESPAsyncTCP.cpp:839:30: error: invalid conversion from 'long int (*)...

### ISSUE THREAD

**Issue by ghislainborremans** [me-no-dev/ESPAsyncTCP#61]
Hello , 
I can not compile due to the erros below:

ESPAsyncTCP\src\ESPAsyncTCP.cpp:839:30: error: invalid conversion from 'long int (*)(void*, tcp_pcb*, long int)' to 'tcp_accept_fn {aka signed char (*)(void*, tcp_pcb*, signed char)}' [-fpermissive]
   tcp_accept(_pcb, &_s_accept);

any help would be appreciated. 

thanks in advance 

Ghislain

**Comment by me-no-dev** [comment]
update your esp8266 arduino to the latest git :)

**Comment by cwca02** [comment]
I'm having the same issue.  I updated esp8266 to the latest and I'm still having it.  Any help would be greatly appreciated.

**Comment by ghislainborremans** [comment]
Updated but it stays the same. ( as reference: i am trying to run the FSBrowserNG UserConfigExample )

**Comment by cwca02** [comment]
Go to c2d4c16.  I just implemented those changes and I'm golden.

**Comment by ghislainborremans** [comment]
This is correct, the above solution works ( i copied the file contents from ESPAsyncTCP.cpp AND ESPAsyncTCP.h )
thans for the support.
