### ISSUE TITLE
Client https (SSL)

### ISSUE THREAD

**Issue by mcmega** [me-no-dev/ESPAsyncTCP#65]
Hi!
ESP8266 (ESP12)
Settings: Default

**I want to do:**
- connect to the server by https (use SSL Fingerprint)
- get only contents of the file *.txt (const char *response = content of file)
- close connection

How to do it right?
```
#define OTA_HOST        "updates.soi-tech.com"
#define OTA_PATH        "/WalkingLight.txt"
#define OTA_SSL_FP      "6A E3 57 ..."

static AsyncClient * aClient = NULL;

void otaAvailable() {
  if (WiFi.status() == WL_CONNECTED) {
    if (aClient) {
      uartSendEA("Client Exists");
      return;
    } else {
      aClient = new AsyncClient();
    }
    if (!aClient) {
      uartSendEA("Couldn't allocate Client");
      return;
    }


  }
}
```
### How can I know the status of the server's response?

**Comment by mcmega** [comment]
Something I can not do anything ...
Tell me please, How to read only contents of a files *.txt, to const char *response = ...?

**Comment by me-no-dev** [comment]
@mcmega sorry but you seem to take github issues as something that is dedicated to user issues. It is not ;) If you want help with your own problems using the lib, this is not the place. Please use Gitter chat for that (link in README). Closing this and most of your other "issues" as well.

**Comment by mcmega** [comment]
Thanks for the answer, but I did not find a link to Gitter

**Comment by me-no-dev** [comment]
<img width="396" alt="screen shot 2017-11-03 at 19 37 51" src="https://user-images.githubusercontent.com/12663778/32387949-b5cb4d4a-c0ce-11e7-9d03-b120d19e8c9c.png">
