### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by marvinroger** [me-no-dev/ESPAsyncTCP#9]
Pretty sure this is already on the roadmap, but this is obviously a needed feature. Keep up the good work!

**Comment by me-no-dev** [comment]
I have already looked into this and the current SSL implementation is synchronous, which prevents it to work in async environment :(

**Comment by marvinroger** [comment]
By current implementation, do you mean axTLS is blocking?

**Comment by me-no-dev** [comment]
yes

**Comment by battuashwik** [comment]
Any update on this. Any directions would be very much appreciated.
