### ISSUE TITLE
POST with JSON having problem

### ISSUE THREAD

**Issue by Perawi** [me-no-dev/ESPAsyncTCP#93]
I tried the code below but received HTTP/1.1 404 Not Found.
The code was modified from "me-no-dev commented on Aug 19, 2016". Only client->write("....") was modified. I worked using Postman and HTTPClient. I tried to make it Asynchronous.
/* ============ Code snippet below ================ */
String test = "POST /api/v0002/application/types/ESP8266/devices/Test1/events/myEvent HTTP/1.1\r\n"; 
     test += "Host: quickstart.messaging.internetofthings.ibmcloud.com:1883\r\n"; 
     test += "Content-Type: application/json\r\n"; 
     test += "Content-Length: 26\r\n\r\n"; 
     test += "{\"d\":{\"aMessage\": 12.9 } }"; 
    strcpy(buff,test.c_str()); 
    client->write(buff); 
    uint8_t ii=0; 
    while (buff[ii]) { 
       Serial1.print(buff[ii]); 
       ii++; 
}

**Comment by RaboliotTheGrey** [comment]
`"{"d":{"aMessage": 12.9 } }";` 

You need to escape  the " with \ like `\"`. 
So it should looks like : `"{\"d\":{\"aMessage\": 12.9 } }";`

Check you Content-length and be aware of the space.
